services:
  front:
    image: viqcinese/my-academy-front:latest
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./zygurat.pro:/etc/letsencrypt/live/zygurat.pro:ro
    environment:
      VITE_AUTH_PROVIDER_DOMAIN: ${AUTH_PROVIDER_DOMAIN}
      VITE_AUTH_PROVIDER_CLIENT_ID: ${AUTH_PROVIDER_CLIENT_ID}
      VITE_AUTH_PROVIDER_AUDIENCE: ${AUTH_PROVIDER_AUDIENCE}
    networks:
      - my-network

  app:
    image: viqcinese/my-academy-app:latest
    restart: always
    ports:
      - "3000:3000"
    environment:
      DATABASE_HOSTNAME: ${DATABASE_HOSTNAME}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_USER_PASSWORD: ${DATABASE_USER_PASSWORD}
      DATABASE_URL: mysql://root:${DATABASE_ROOT_PASSWORD}@${DATABASE_HOSTNAME}:${DATABASE_PORT}/${DATABASE_NAME}
      AUTH_PROVIDER_DOMAIN: ${AUTH_PROVIDER_DOMAIN}
      AUTH_PROVIDER_CLIENT_ID: ${AUTH_PROVIDER_CLIENT_ID}
      AUTH_PROVIDER_AUDIENCE: ${AUTH_PROVIDER_AUDIENCE}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - my-network

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${DATABASE_USER_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - my_sql:/var/lib/mysql
    networks:
      - my-network
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "-p${MYSQL_ROOT_PASSWORD}",
        ]
      interval: 5s
      retries: 10
      start_period: 30s
      timeout: 10s

volumes:
  my_sql:

networks:
  my-network:
    driver: bridge
