name: Deploy to VM

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and Push Backend Image
        run: |
          docker build -t viqcinese/my-academy-app:latest -f app/Dockerfile.prod app
          docker tag viqcinese/my-academy-app:latest viqcinese/my-academy-app:latest
          docker push viqcinese/my-academy-app:latest

      - name: Build and Push Frontend Image
        run: |
          docker build -t viqcinese/my-academy-front:latest -f front/Dockerfile.prod front
          docker tag viqcinese/my-academy-front:latest viqcinese/my-academy-front:latest
          docker push viqcinese/my-academy-front:latest

      - name: Copy `docker-compose.prod.yml` to VM
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          source: "docker-compose.prod.yml"
          target: "~/my-academy"

      - name: Deploy to VM
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            cd ~/my-academy
            echo "${{ secrets.ENV_FILE }}" > .env
            docker pull viqcinese/my-academy-app:latest
            docker pull viqcinese/my-academy-front:latest
            docker compose -f ./docker-compose.prod.yml up -d --force-recreate
